project:
  type: book
  output-dir: docs

book:
  title: "Módulos 5 y 6"
  subtitle: "Diplomado IA en Salud"
  author: "David Escudero García"
  date: "8/31/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - plan-estrategico.qmd
    - colaboracion.qmd
    - Clasificador.qmd
    - Entrenamiento.qmd
    - Interpretacion.qmd
    - Evaluacion.qmd
    - sesgos.qmd
    - plan-neumonia.qmd
    - presentacion.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: flatly
  pdf:
    documentclass: scrreprt



