project:
  type: book
  output-dir: docs

book:
  title: "Modulo 5"
  subtitle: "Diplomado IA en Salud"
  author: "David Escudero García"
  date: "8/31/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - plan-estrategico.qmd
    - plan-neumonia.qmd
    - presentacion.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: flatly
  pdf:
    documentclass: scrreprt



